<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <AssemblyName>Theseus</AssemblyName>
    <RootNamespace>Theseus</RootNamespace>
    <Version>0.1.0</Version>
    <DalamudLibPath>$(AppData)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
  </PropertyGroup>

  <!-- Allow the test assembly to access internal types -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Theseus.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
